title: My Website Blog
description: This is my blog for my website.

theme: minima

email: rnts3d@outlook.com
  
show_excerpts: true
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Optional configurations
url: "https://your-website-url.com"  # Replace with your actual URL
baseurl: ""  # Leave empty for root or set it if hosted in a subfolder

# Collections configuration (if needed)
collections:
  posts:
    output: true

# Google Analytics or other tracking setup (if applicable)
# google_analytics: UA-XXXXX-Y

# Enable RSS feed
feed:
  path: /atom.xml

# Enable SEO Tags for Jekyll
seo:
  title: "My Website Blog"
  description: "This is my blog for my website."
  url: "https://your-website-url.com"  # Replace with your actual URL

# Permalink configuration
permalink: "/:year/:month/:day/:title/"

# Additional configurations for customizing layouts
defaults:
  - scope:
      path: ""  # Default for the entire site
    values:
      layout: "default"

# Optional: you can add any custom configuration here, such as for social media or third-party integrations
