title: My Website Blog
description: This is my blog for my website.

theme: minima

email: rnts3d@outlook.com
  
show_excerpts: true
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

---
---

@import "minima";

body {
  font-family: 'Inter', sans-serif;
  background-color: #fdfcfb;
  color: #333;
}

a {
  color: #1e90ff;
}
